# Generated by Django 2.2.12 on 2021-07-22 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sprint_subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceUsageRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("usage_date", models.DateTimeField()),
                ("seconds_used", models.IntegerField()),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sprint_subscriptions.SprintSubscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataUsageRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("usage_date", models.DateTimeField()),
                ("kilobytes_used", models.IntegerField()),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sprint_subscriptions.SprintSubscription",
                    ),
                ),
            ],
        ),
    ]
