# Generated by Django 2.2.12 on 2021-07-28 11:42

from django.db import migrations


def run_sql_query_file(query_file):
    with open(query_file) as file:
        query = file.read()
    return query


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(run_sql_query_file(query_file="union_data_id_fields.sql")),
        migrations.RunSQL(run_sql_query_file(query_file="usage_metrics_joins.sql")),
    ]
